#!/bin/sh

set -e
BASE=/root/posix_tmpfs
SRC="$BASE/posix_tmpfs.c"
BIN="$BASE/posix_tmpfs"

fail()
{
	echo "posix_tmpfs: $1" >&2
	exit 1
}

expect_success()
{
	set +e
	output=$("$@" 2>&1)
	rc=$?
	set -e
	[ "$rc" -eq 0 ] && return 0
	fail "Expected: success from '$*'
Actual: exit status $rc
Output: ${output:-<none>}"
}

require_cmd()
{
	command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"
}

cleanup()
{
	rm -rf "$BASE" >/dev/null 2>&1 || true
	rm -f /dev/shm/posix_tmpfs_test.bin >/dev/null 2>&1 || true
	rm -rf /dev/shm/posix_tmpfs_dir >/dev/null 2>&1 || true
}

trap cleanup EXIT
cleanup

require_cmd gcc

mkdir -p "$BASE" >/dev/null 2>&1 || fail "mkdir failed"

printf '%s\n' '#include <sys/types.h>' > "$SRC"
printf '%s\n' '#include <sys/stat.h>' >> "$SRC"
printf '%s\n' '#include <sys/mman.h>' >> "$SRC"
printf '%s\n' '#include <dirent.h>' >> "$SRC"
printf '%s\n' '#include <fcntl.h>' >> "$SRC"
printf '%s\n' '#include <utime.h>' >> "$SRC"
printf '%s\n' '#include <unistd.h>' >> "$SRC"
printf '%s\n' '#include <errno.h>' >> "$SRC"
printf '%s\n' '#include <stdio.h>' >> "$SRC"
printf '%s\n' '#include <stdlib.h>' >> "$SRC"
printf '%s\n' '#include <string.h>' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '#define FILE_PATH "/dev/shm/posix_tmpfs_test.bin"' >> "$SRC"
printf '%s\n' '#define DIR_PATH "/dev/shm/posix_tmpfs_dir"' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' 'static int failf(const char *msg)' >> "$SRC"
printf '%s\n' '{' >> "$SRC"
printf '%s\n' '	fprintf(stderr, "%s\n", msg);' >> "$SRC"
printf '%s\n' '	return 1;' >> "$SRC"
printf '%s\n' '}' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' 'static int fail_errno(const char *what)' >> "$SRC"
printf '%s\n' '{' >> "$SRC"
printf '%s\n' '	fprintf(stderr, "%s: %s\n", what, strerror(errno));' >> "$SRC"
printf '%s\n' '	return 1;' >> "$SRC"
printf '%s\n' '}' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' 'static int expect_zero_region(const char *buf, size_t start, size_t end, const char *what)' >> "$SRC"
printf '%s\n' '{' >> "$SRC"
printf '%s\n' '	size_t i;' >> "$SRC"
printf '%s\n' '	for (i = start; i < end; i++) {' >> "$SRC"
printf '%s\n' '		if ((unsigned char)buf[i] != 0) {' >> "$SRC"
printf '%s\n' '			fprintf(stderr, "%s: byte %lu was 0x%02x, expected 0x00\n",' >> "$SRC"
printf '%s\n' '				what, (unsigned long)i, (unsigned char)buf[i]);' >> "$SRC"
printf '%s\n' '			return 1;' >> "$SRC"
printf '%s\n' '		}' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	return 0;' >> "$SRC"
printf '%s\n' '}' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' 'int main(void)' >> "$SRC"
printf '%s\n' '{' >> "$SRC"
printf '%s\n' '	int fd;' >> "$SRC"
printf '%s\n' '	ssize_t n;' >> "$SRC"
printf '%s\n' '	struct stat st;' >> "$SRC"
printf '%s\n' '	struct utimbuf ut;' >> "$SRC"
printf '%s\n' '	char buf[256];' >> "$SRC"
printf '%s\n' '	char c;' >> "$SRC"
printf '%s\n' '	DIR *dir;' >> "$SRC"
printf '%s\n' '	struct dirent *de;' >> "$SRC"
printf '%s\n' '	int saw_dot = 0, saw_dotdot = 0;' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	unlink(FILE_PATH);' >> "$SRC"
printf '%s\n' '	rmdir(DIR_PATH);' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	fd = open(FILE_PATH, O_CREAT | O_RDWR | O_TRUNC, 0600);' >> "$SRC"
printf '%s\n' '	if (fd < 0)' >> "$SRC"
printf '%s\n' '		return fail_errno("open file");' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	memset(buf, 0x5a, sizeof(buf));' >> "$SRC"
printf '%s\n' '	if (write(fd, buf, 128) != 128) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("write initial");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (ftruncate(fd, 17) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("ftruncate shrink");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (ftruncate(fd, 128) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("ftruncate regrow");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (lseek(fd, 0, SEEK_SET) < 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("lseek after regrow");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	memset(buf, 0, sizeof(buf));' >> "$SRC"
printf '%s\n' '	n = read(fd, buf, 128);' >> "$SRC"
printf '%s\n' '	if (n != 128) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "read after regrow returned %ld, expected 128\n", (long)n);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (buf[0] != 0x5a || buf[16] != 0x5a)' >> "$SRC"
printf '%s\n' '		return failf("truncate preserved bytes before new EOF incorrectly");' >> "$SRC"
printf '%s\n' '	if (expect_zero_region(buf, 17, 128, "truncate regrow zero-fill") != 0)' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	if (ftruncate(fd, 5) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("ftruncate small");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (lseek(fd, 20, SEEK_SET) < 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("lseek sparse");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	c = '\''Q'\'';' >> "$SRC"
printf '%s\n' '	if (write(fd, &c, 1) != 1) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("write sparse");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (lseek(fd, 0, SEEK_SET) < 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("lseek read sparse");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	memset(buf, 0, sizeof(buf));' >> "$SRC"
printf '%s\n' '	n = read(fd, buf, 21);' >> "$SRC"
printf '%s\n' '	if (n != 21) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "read sparse returned %ld, expected 21\n", (long)n);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (buf[0] != 0x5a || buf[4] != 0x5a)' >> "$SRC"
printf '%s\n' '		return failf("sparse write corrupted preserved prefix");' >> "$SRC"
printf '%s\n' '	if (expect_zero_region(buf, 5, 20, "sparse write zero-fill") != 0)' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	if (buf[20] != '\''Q'\'')' >> "$SRC"
printf '%s\n' '		return failf("sparse write final byte mismatch");' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	if (chmod(FILE_PATH, 0640) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("chmod");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (stat(FILE_PATH, &st) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("stat after chmod");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if ((st.st_mode & 0777) != 0640) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "chmod mode was %03o, expected 640\n", st.st_mode & 0777);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	if (chown(FILE_PATH, 123, 456) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("chown");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (stat(FILE_PATH, &st) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("stat after chown");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (st.st_uid != 123 || st.st_gid != 456) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "chown result was uid=%lu gid=%lu, expected 123:456\n",' >> "$SRC"
printf '%s\n' '			(unsigned long)st.st_uid, (unsigned long)st.st_gid);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	ut.actime = 111111111u;' >> "$SRC"
printf '%s\n' '	ut.modtime = 222222222u;' >> "$SRC"
printf '%s\n' '	if (utime(FILE_PATH, &ut) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("utime");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if (stat(FILE_PATH, &st) != 0) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		return fail_errno("stat after utime");' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	if ((unsigned long)st.st_atime != 111111111u || (unsigned long)st.st_mtime != 222222222u) {' >> "$SRC"
printf '%s\n' '		close(fd);' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "utime result was atime=%lu mtime=%lu, expected 111111111/222222222\n",' >> "$SRC"
printf '%s\n' '			(unsigned long)st.st_atime, (unsigned long)st.st_mtime);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	close(fd);' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	if (mkdir(DIR_PATH, 0755) != 0)' >> "$SRC"
printf '%s\n' '		return fail_errno("mkdir tmpfs dir");' >> "$SRC"
printf '%s\n' '	if (stat(DIR_PATH, &st) != 0)' >> "$SRC"
printf '%s\n' '		return fail_errno("stat dir");' >> "$SRC"
printf '%s\n' '	if (st.st_nlink != 2) {' >> "$SRC"
printf '%s\n' '		fprintf(stderr, "empty dir nlink was %lu, expected 2\n", (unsigned long)st.st_nlink);' >> "$SRC"
printf '%s\n' '		return 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	dir = opendir(DIR_PATH);' >> "$SRC"
printf '%s\n' '	if (!dir)' >> "$SRC"
printf '%s\n' '		return fail_errno("opendir");' >> "$SRC"
printf '%s\n' '	while ((de = readdir(dir)) != NULL) {' >> "$SRC"
printf '%s\n' '		if (strcmp(de->d_name, ".") == 0)' >> "$SRC"
printf '%s\n' '			saw_dot = 1;' >> "$SRC"
printf '%s\n' '		else if (strcmp(de->d_name, "..") == 0)' >> "$SRC"
printf '%s\n' '			saw_dotdot = 1;' >> "$SRC"
printf '%s\n' '	}' >> "$SRC"
printf '%s\n' '	closedir(dir);' >> "$SRC"
printf '%s\n' '	if (!saw_dot || !saw_dotdot)' >> "$SRC"
printf '%s\n' '		return failf("readdir did not report . and .. for tmpfs directory");' >> "$SRC"
printf '%s\n' '' >> "$SRC"
printf '%s\n' '	if (unlink(DIR_PATH) == 0)' >> "$SRC"
printf '%s\n' '		return failf("unlink unexpectedly succeeded on tmpfs directory");' >> "$SRC"
printf '%s\n' '	if (rmdir(DIR_PATH) != 0)' >> "$SRC"
printf '%s\n' '		return fail_errno("rmdir tmpfs dir");' >> "$SRC"
printf '%s\n' '	if (unlink(FILE_PATH) != 0)' >> "$SRC"
printf '%s\n' '		return fail_errno("unlink tmpfs file");' >> "$SRC"
printf '%s\n' '	return 0;' >> "$SRC"
printf '%s\n' '}' >> "$SRC"

expect_success gcc -o "$BIN" "$SRC"
[ -x "$BIN" ] || fail "compiled helper missing"
expect_success "$BIN"
