#!/bin/sh

set -eu

out=$1
path=$2
case_mtime=$(date -r "$path" +%Y%m%d%H%M.%S)

{
	printf '/* Auto-generated by tools/gen_ktest_scripts.sh. */\n'
	printf '#include <test/test.h>\n\n'

	base=${path##*/}
	name=${base%.sh}
	symbol=$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_]/_/g')

	printf 'static const char _ktest_script_%s[] =\n' "$symbol"
	awk -v case_mtime="$case_mtime" '
		{
			gsub(/@CASE_MTIME@/, case_mtime);
			gsub(/\\/, "\\\\");
			gsub(/"/, "\\\"");
			printf "\t\"%s\\n\"\n", $0;
		}
		END {
			if (NR == 0)
				printf "\t\"\"\n";
		}
	' "$path"
	printf '\t;\n'
	printf 'KTEST_SCRIPT_NAMED("%s", _ktest_script_%s);\n' \
		"$name" "$symbol"
} > "$out"
