#ifndef MOS_X86_ARCH_CONFIG_H
#define MOS_X86_ARCH_CONFIG_H

#define KERNEL_PRIVILEGE 0
#define USER_PRIVILEGE 3

#define NULL_SELECTOR 0x0
#define KERNEL_DATA_SELECTOR 0x8
#define KERNEL_CODE_SELECTOR 0x10
#define USER_DATA_SELECTOR 0x1b
#define USER_CODE_SELECTOR 0x23
#define ADDRESS_LIMIT 0xfffff

#define SEG_CLASS_DATA 1
#define SEG_CLASS_SYSTEM 0
#define SEG_BASE_4K 1
#define SEG_BASE_1 0
#define TSS_SEG_BASE SEG_BASE_1

#define GDT_ENTRY_TLS_MIN 6
#define GDT_ENTRY_TLS_MAX 8
#define GDT_ENTRY_TLS_COUNT 3
#define TSS_SELECTOR ((GDT_ENTRY_TLS_MAX + 1) << 3)
#define CPU_LOCAL_SELECTOR (10 << 3)

#define SYSCALL_INT_NO 0x80

#define LDT_ENTRY_COUNT 16
#define LDT_SELECTOR ((5 + GDT_ENTRY_TLS_COUNT + 1) << 3)
#define SELECTOR_COUNT 11

/* Architecture memory model. Keep these here so common VM code does not
 * encode i386's 32-bit layout. */
#define MOS_UTS_MACHINE "i686"
#define MOS_KERNEL_OFFSET 0xC0000000UL
#define MOS_KERNEL_SIZE 0x40000000UL
#define MOS_KERNEL_KMAP_BEGIN 0xF0000000UL
#define MOS_KERNEL_KMAP_END 0xF8000000UL
#define MOS_KERNEL_IO_BEGIN MOS_KERNEL_KMAP_END
#define MOS_KERNEL_IO_END 0x100000000ULL
#define MOS_PAGE_SIZE 0x1000UL
#define MOS_PAGE_SIZE_MASK 0xFFFFF000UL
#define MOS_PG_TABLE_SIZE 1024
#define MOS_PE_TABLE_SIZE 1024
#define MOS_KERNEL_PAGE_DIR_OFFSET (MOS_KERNEL_OFFSET / (4 * 1024 * 1024))
#define MOS_KERNEL_HEAP_BEGIN 0xC0700000UL
#define MOS_KERNEL_HEAP_SIZE 0x004FF000UL
#define MOS_TASK_UNMAPPED_BASE (MOS_KERNEL_OFFSET / 3)
#define MOS_OFFSET_IN_PET_MASK 0x003FF000UL
#define MOS_OFFSET_IN_PGT_MASK 0xFFC00000UL
#define MOS_PGT_SHIFT 22
#define MOS_PET_SHIFT 12

#endif
