#ifndef MOS_X86_ARCH_CONFIG_H
#define MOS_X86_ARCH_CONFIG_H

#define KERNEL_PRIVILEGE 0
#define USER_PRIVILEGE 3

#define NULL_SELECTOR 0x0
#define KERNEL_DATA_SELECTOR 0x8
#define KERNEL_CODE_SELECTOR 0x10
#define USER_DATA_SELECTOR 0x1b
#define USER_CODE_SELECTOR 0x23
#define ADDRESS_LIMIT 0xfffff

#define SEG_CLASS_DATA 1
#define SEG_CLASS_SYSTEM 0
#define SEG_BASE_4K 1
#define SEG_BASE_1 0
#define TSS_SEG_BASE SEG_BASE_1

#define GDT_ENTRY_TLS_MIN 6
#define GDT_ENTRY_TLS_MAX 8
#define GDT_ENTRY_TLS_COUNT 3
#define TSS_SELECTOR ((GDT_ENTRY_TLS_MAX + 1) << 3)
#define CPU_LOCAL_SELECTOR (10 << 3)

#define SYSCALL_INT_NO 0x80

#define LDT_ENTRY_COUNT 16
#define LDT_SELECTOR ((5 + GDT_ENTRY_TLS_COUNT + 1) << 3)
#define SELECTOR_COUNT 11

#endif
