name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gcc x86 support
      run: sudo apt update && sudo apt install gcc-multilib -y
    - name: make
      run: make
